### ISSUE TITLE
httpdns: request http://null:80/100000/d?host=www.taobao.com&sdk=android_0.0.0.1-local-SNAPSHOT&sid=PSzzR8nQVUdH fail

### ISSUE THREAD

**Issue by GreatDongsong** [aliyun/alibabacloud-httpdns-android-sdk#3]
while  i run the demo,  i got this issue:

2021-12-15 10:03:50.936 22461-22628/com.aliyun.ams.httpdns.demo D/httpdns: request host www.taobao.com with type v4 extras : null cacheKey null
2021-12-15 10:03:50.937 22461-22628/com.aliyun.ams.httpdns.demo D/test: from sdk: [D]request host www.taobao.com with type v4 extras : null cacheKey null
2021-12-15 10:03:50.937 22461-22628/com.aliyun.ams.httpdns.demo D/httpdns: host www.taobao.com result is null
2021-12-15 10:03:50.938 22461-22628/com.aliyun.ams.httpdns.demo D/test: from sdk: [D]host www.taobao.com result is null
2021-12-15 10:03:50.938 22461-22628/com.aliyun.ams.httpdns.demo D/httpdns: start async ip request for www.taobao.com v4
2021-12-15 10:03:50.939 22461-22628/com.aliyun.ams.httpdns.demo D/test: from sdk: [D]start async ip request for www.taobao.com v4
2021-12-15 10:03:50.940 22461-22628/com.aliyun.ams.httpdns.demo I/httpdns: request host www.taobao.com and return empty immediately
2021-12-15 10:03:50.941 22461-22628/com.aliyun.ams.httpdns.demo D/test: from sdk: [I]request host www.taobao.com and return empty immediately
2021-12-15 10:03:50.941 22461-22628/com.aliyun.ams.httpdns.demo D/tt: cost time: 5
2021-12-15 10:03:50.942 22461-25083/com.aliyun.ams.httpdns.demo D/httpdns: request url http://null:80/100000/d?host=www.taobao.com&sdk=android_0.0.0.1-local-SNAPSHOT&sid=PSzzR8nQVUdH
2021-12-15 10:03:50.943 22461-25083/com.aliyun.ams.httpdns.demo D/test: from sdk: [D]request url http://null:80/100000/d?host=www.taobao.com&sdk=android_0.0.0.1-local-SNAPSHOT&sid=PSzzR8nQVUdH
2021-12-15 10:03:50.959 22461-25083/com.aliyun.ams.httpdns.demo E/httpdns: request http://null:80/100000/d?host=www.taobao.com&sdk=android_0.0.0.1-local-SNAPSHOT&sid=PSzzR8nQVUdH fail, cost 15
2021-12-15 10:03:50.959 22461-25083/com.aliyun.ams.httpdns.demo D/test: from sdk: [W]request http://null:80/100000/d?host=www.taobao.com&sdk=android_0.0.0.1-local-SNAPSHOT&sid=PSzzR8nQVUdH fail, cost 15
2021-12-15 10:03:50.960 22461-25083/com.aliyun.ams.httpdns.demo D/test: from sdk: 
2021-12-15 10:03:50.961 22461-25083/com.aliyun.ams.httpdns.demo W/System.err: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
2021-12-15 10:03:50.961 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.alibaba.sdk.android.httpdns.d.d.a(Unknown Source:8)
2021-12-15 10:03:50.962 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.alibaba.sdk.android.httpdns.interpret.n.a(Unknown Source:32)
2021-12-15 10:03:50.962 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.alibaba.sdk.android.httpdns.g.g.a(Unknown Source:50)
2021-12-15 10:03:50.963 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.alibaba.sdk.android.httpdns.g.h.a(Unknown Source:2)
2021-12-15 10:03:50.963 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.alibaba.sdk.android.httpdns.g.l.a(Unknown Source:0)
2021-12-15 10:03:50.964 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.alibaba.sdk.android.httpdns.g.f.a(Unknown Source:2)
2021-12-15 10:03:50.964 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.alibaba.sdk.android.httpdns.g.a.run(Unknown Source:0)
2021-12-15 10:03:50.965 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021-12-15 10:03:50.965 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-12-15 10:03:50.966 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at java.lang.Thread.run(Thread.java:923)
2021-12-15 10:03:50.966 22461-25083/com.aliyun.ams.httpdns.demo D/httpdns: request url http://null:80/100000/d?host=www.taobao.com&sdk=android_0.0.0.1-local-SNAPSHOT&sid=PSzzR8nQVUdH
2021-12-15 10:03:50.966 22461-25083/com.aliyun.ams.httpdns.demo D/test: from sdk: [D]request url http://null:80/100000/d?host=www.taobao.com&sdk=android_0.0.0.1-local-SNAPSHOT&sid=PSzzR8nQVUdH
2021-12-15 10:03:50.979 22461-25083/com.aliyun.ams.httpdns.demo E/httpdns: request http://null:80/100000/d?host=www.taobao.com&sdk=android_0.0.0.1-local-SNAPSHOT&sid=PSzzR8nQVUdH fail, cost 13
2021-12-15 10:03:50.980 22461-25083/com.aliyun.ams.httpdns.demo D/test: from sdk: [W]request http://null:80/100000/d?host=www.taobao.com&sdk=android_0.0.0.1-local-SNAPSHOT&sid=PSzzR8nQVUdH fail, cost 13
2021-12-15 10:03:50.980 22461-25083/com.aliyun.ams.httpdns.demo D/test: from sdk: 
2021-12-15 10:03:50.980 22461-25083/com.aliyun.ams.httpdns.demo W/System.err: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
2021-12-15 10:03:50.980 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.alibaba.sdk.android.httpdns.d.d.a(Unknown Source:8)
2021-12-15 10:03:50.981 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.alibaba.sdk.android.httpdns.interpret.n.a(Unknown Source:32)
2021-12-15 10:03:50.981 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.alibaba.sdk.android.httpdns.g.g.a(Unknown Source:50)
2021-12-15 10:03:50.981 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.alibaba.sdk.android.httpdns.g.h.a(Unknown Source:2)
2021-12-15 10:03:50.981 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.alibaba.sdk.android.httpdns.g.l.a(Unknown Source:0)
2021-12-15 10:03:50.982 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.alibaba.sdk.android.httpdns.g.f.a(Unknown Source:2)
2021-12-15 10:03:50.982 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.alibaba.sdk.android.httpdns.g.a.run(Unknown Source:0)
2021-12-15 10:03:50.982 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021-12-15 10:03:50.982 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-12-15 10:03:50.983 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at java.lang.Thread.run(Thread.java:923)
2021-12-15 10:03:50.983 22461-25083/com.aliyun.ams.httpdns.demo W/System.err: java.net.UnknownHostException: Unable to resolve host "null": No address associated with hostname
2021-12-15 10:03:50.983 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:124)
2021-12-15 10:03:50.984 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
2021-12-15 10:03:50.984 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at java.net.InetAddress.getAllByName(InetAddress.java:1152)
2021-12-15 10:03:50.984 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.android.okhttp.Dns$1.lookup(Dns.java:41)
2021-12-15 10:03:50.984 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)
2021-12-15 10:03:50.985 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
2021-12-15 10:03:50.985 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)
2021-12-15 10:03:50.985 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:176)
2021-12-15 10:03:50.986 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
2021-12-15 10:03:50.986 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
2021-12-15 10:03:50.986 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
2021-12-15 10:03:50.987 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
2021-12-15 10:03:50.987 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
2021-12-15 10:03:50.987 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
2021-12-15 10:03:50.988 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
2021-12-15 10:03:50.988 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.alibaba.sdk.android.httpdns.g.c.a(Unknown Source:81)
2021-12-15 10:03:50.988 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.alibaba.sdk.android.httpdns.g.h.a(Unknown Source:2)
2021-12-15 10:03:50.988 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.alibaba.sdk.android.httpdns.g.g.a(Unknown Source:18)
2021-12-15 10:03:50.988 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.alibaba.sdk.android.httpdns.g.h.a(Unknown Source:2)
2021-12-15 10:03:50.989 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.alibaba.sdk.android.httpdns.g.g.a(Unknown Source:18)
2021-12-15 10:03:50.989 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.alibaba.sdk.android.httpdns.g.h.a(Unknown Source:2)
2021-12-15 10:03:50.989 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.alibaba.sdk.android.httpdns.g.g.a(Unknown Source:18)
2021-12-15 10:03:50.989 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.alibaba.sdk.android.httpdns.g.h.a(Unknown Source:2)
2021-12-15 10:03:50.990 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.alibaba.sdk.android.httpdns.g.l.a(Unknown Source:0)
2021-12-15 10:03:50.990 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.alibaba.sdk.android.httpdns.g.f.a(Unknown Source:2)
2021-12-15 10:03:50.990 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at com.alibaba.sdk.android.httpdns.g.a.run(Unknown Source:0)
2021-12-15 10:03:50.990 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021-12-15 10:03:50.991 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-12-15 10:03:50.991 22461-25083/com.aliyun.ams.httpdns.demo W/System.err:     at java.lang.Thread.run(Thread.java:923)
2021-12-15 10:03:50.992 22461-25083/com.aliyun.ams.httpdns.demo E/httpdns: ip request for www.taobao.com fail
2021-12-15 10:03:50.992 22461-25083/com.aliyun.ams.httpdns.demo D/test: from sdk: [W]ip request for www.taobao.com fail
2021-12-15 10:03:50.992 22461-25083/com.aliyun.ams.httpdns.demo D/test: from sdk:

**Comment by new-xd** [comment]
http://null:80/100000/d?host=www.taobao.com&sdk=android_0.0.0.1-local-SNAPSHOT&sid=PSzzR8nQVUdH

You need config server ip in gradle.properties. You can try 203.107.1.33 to run demo.
INIT_SERVERS={"203.107.1.33"}
